services:
  saltmaster:
    image: saltmaster:3003.1-ubuntu
    build:
      context: .
      dockerfile: ./master.dockerfile
    command: ['-l', 'debug']

  saltminion:
    image: saltminion:3003.1-ubuntu
    build:
      context: .
      dockerfile: ./minion.dockerfile
    command: ['-l', 'debug']
